CREATE DATABASE blog;

CREATE TABLE Categories(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name_category VARCHAR(255) NOT NULL,
createdAt TIMESTAMP,
updatedAt TIMESTAMP
);

CREATE TABLE Posts(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
content VARCHAR(500) NOT NULL,
image VARCHAR(300) NOT NULL,
create_date DATE NOT NULL,
createdAt TIMESTAMP,
updatedAt TIMESTAMP,
id_category INT NOT NULL,
CONSTRAINT FK_id_category FOREIGN KEY (id_category)
REFERENCES Categories(id)
);